apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pvc
spec:
  storageClassName: seaweedfs-storage-nvme
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
