apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jawad-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
