apiVersion: v1
kind: Pod
metadata:
  name: segmentation-pod

spec:
  containers:
    - name: gpu-container
      image: ubuntu
      volumeMounts:
        - name: segmentation-project-vol
          mountPath: /project
        - name: git-repo
          mountPath: /opt/repo
      resources:
        limits:
          memory: "8Gi"
          cpu: "4"
          nvidia.com/gpu: "2"
        requests:
          memory: "8Gi"
          cpu: "4"
          nvidia.com/gpu: "2"
      command:
        - "sh"
        - "-c"
        - |
          apt-get update && \
          apt-get install -y git && \
          git clone https://github.com/mahfuzalhasan/multi-region-attention /opt/repo/mra && \
          apt update && \
          echo 'Commands executed successfully.' && \
          sleep infinity

  volumes:
    - name: git-repo
      emptyDir: {}
    - name: segmentation-project-vol
      persistentVolumeClaim:
        claimName: project-pvc