apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A100-SXM4-80GB
  containers:
  - name: t-pod
    image: ubuntu
    volumeMounts:
    - mountPath: /project
      name: project
    resources:
      limits:
        memory: 32Gi
        cpu: "4"
      requests:
        memory: 32Gi
        cpu: "4"
    command: 
      - "sh"
      - "-c"
      - |
        apt update && \
        apt install -y wget unzip python3 python3-pip git && \
        echo '===========Commands executed successfully.==========' && \
        sleep infinity
  volumes:
    - name: project
      persistentVolumeClaim:
        claimName: project-pvc
