apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-RTX-A6000
  containers:
  - name: t-pod
    image: ubuntu
    volumeMounts:
    - mountPath: /project
      name: project
    resources:
      limits:
        memory: 32Gi
        cpu: "4"
        nvidia.com/gpu: "2"
      requests:
        memory: 32Gi
        cpu: "4"
        nvidia.com/gpu: "2"
    command: 
      - "sh"
      - "-c"
      - |
        apt update && \
        apt install -y python3 python3-pip && \
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 && \
        pip3 install timm==0.9.7 && \
        pip3 install easydict==1.10 && \
        pip3 install datasets && \
        pip3 install termcolor && \
        pip3 install tensorboardX && \
        pip3 install -U "huggingface_hub[cli]" && \
        huggingface-cli login --token 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 && \
        apt-get update && \
        apt-get install -y git && \
        echo '===========installation successful==========' && \
        mkdir -p /opt/repo/multi-region-attention && \
        git clone --single-branch --branch ms-head-attn-conv-merge https://github.com/mahfuzalhasan/multi-region-attention /opt/repo/multi-region-attention && \
        apt update && \
        echo 'git pulled successfully.' && \
        cd /opt/repo/multi-region-attention && \
        torchrun --standalone --nproc_per_node=2 validation_only_local.py imagenet --devices 2 --batchsize 16 && \
        echo '===========Commands executed successfully.==========' && \
        sleep infinity
  volumes:
    - name: project
      persistentVolumeClaim:
        claimName: jawad-pvc
  restartPolicy: Never
