apiVersion: batch/v1
kind: Job
metadata:
  name: seg-job
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-2080-Ti
      containers:
      - name: seg-container
        image: ubuntu
        command:
          - sh
          - -c
          - |
            apt update && \
            apt install -y wget unzip python3 python3-pip git && \
            pip3 install notebook tqdm jupyter && \
            pip3 install torch torchvision torchaudio && \
            pip3 install timm==0.9.7 && \
            pip3 install easydict==1.10 && \
            pip3 install datasets && \
            pip3 install termcolor && \
            pip3 install tensorboardX && \
            pip3 install -U "huggingface_hub[cli]" && \
            huggingface-cli login --token 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 && \
            echo '===========installation successful=========='
            mkdir /opt/repo && \
            cp /project/multi-region-attention.zip /opt/repo && \
            cd /opt/repo && \
            unzip  multi-region-attention.zip && \
            echo '===========unzip successfully=========='
            cd multi-region-attention && \
            python3 train.py imagenet && \
            echo '===========training executed successfully=========='
        volumeMounts:
        - name: data
          mountPath: /project
        resources:
          limits:
            memory: 84Gi
            cpu: "10"
            nvidia.com/gpu: "8"
          requests:
            memory: 84Gi
            cpu: "10"
            nvidia.com/gpu: "8"
        securityContext:
          runAsUser: 0
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: project-pvc
      restartPolicy: Never
  backoffLimit: 0



# https://$(jawadefaj):$(-----)@$(mahfuzalhasan/multi-region-attention)
# - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/bbateni/map-genration-mingpt-job
# - sh
# - -c
# - >
#   apt update &&
#   apt install -y git python3-pip &&
#   git clone https://github.com/mahfuzalhasan/multi-region-attention.git /opt/repo/multi-region-attention &&
#   cd /project &&
#   mkdir models &&
#   cd /opt/repo/multi-region-attention &&
#   pip3 install -r requirements.txt &&
#   cp -r models/* /project/models-pv/
# apt-get update && \
# apt-get install -y git && \
# git clone https://github.com/mahfuzalhasan/multi-region-attention /opt/repo/mra && \
# apt update && \
# echo 'Commands executed successfully.' && \
# sleep infinity

# cd /opt/repo/multi-region-attention && \
# pip3 install -r requirements.txt && \