apiVersion: batch/v1
kind: Job
metadata:
  name: seg-job
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080-Ti
      containers:
      - name: seg-container
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
        command:
          - sh
          - -c
          - |
            apt update && \
            apt install -y wget unzip python3 python3-pip git && \
            pip3 install notebook tqdm jupyter && \
            pip3 install torch torchvision torchaudio && \
            pip3 install timm==0.9.7 && \
            pip3 install easydict==1.10 && \
            pip3 install datasets && \
            pip3 install termcolor && \
            echo '===========Commands executed successfully.==========' && \
            cd /project/multi-region-attention && \
            python3 train.py imagenet
        volumeMounts:
        - name: data
          mountPath: /project
        resources:
          limits:
            memory: 84Gi
            cpu: "4"
            nvidia.com/gpu: "2"
          requests:
            memory: 84Gi
            cpu: "4"
            nvidia.com/gpu: "2"
        securityContext:
          runAsUser: 0
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      restartPolicy: Never
  backoffLimit: 1
