apiVersion: batch/v1
kind: Job
metadata:
  name: seg-job
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
      containers:
      - name: seg-container
        image: ubuntu
        command:
          - sh
          - -c
          - |
            apt update && \
            apt install -y python3 python3-pip && \
            pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 && \
            pip3 install timm==0.9.7 && \
            pip3 install easydict==1.10 && \
            pip3 install datasets && \
            pip3 install termcolor && \
            pip3 install tensorboardX && \
            pip3 install -U "huggingface_hub[cli]" && \
            huggingface-cli login --token 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 && \
            apt-get update && \
            apt-get install -y git && \
            echo '===========installation successful==========' && \
            mkdir -p /opt/repo/multi-region-attention && \
            git clone --single-branch --branch DP_Training https://github.com/mahfuzalhasan/multi-region-attention /opt/repo/multi-region-attention && \
            apt update && \
            echo 'git pulled successfully.' && \
            cd /opt/repo/multi-region-attention && \
            python3 train.py imagenet && \
            echo '===========training executed successfully=========='
        volumeMounts:
        - name: data
          mountPath: /project
        - name: dshm
          mountPath: /dev/shm
        resources:
          limits:
            ephemeral-storage: "700Gi"
            memory: 300Gi
            cpu: "30"
            nvidia.com/gpu: "4"
          requests:
            ephemeral-storage: "700Gi"
            memory: 300Gi
            cpu: "15"
            nvidia.com/gpu: "4"
        securityContext:
          runAsUser: 0
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: data
        persistentVolumeClaim:
          claimName: project-pvc
      restartPolicy: Never
  backoffLimit: 0



# https://$(jawadefaj):$(-----)@$(mahfuzalhasan/multi-region-attention)
# - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/bbateni/map-genration-mingpt-job
# - sh
# - -c
# - >
#   apt update &&
#   apt install -y git python3-pip &&
#   git clone https://github.com/mahfuzalhasan/multi-region-attention.git /opt/repo/multi-region-attention &&
#   cd /project &&
#   mkdir models &&
#   cd /opt/repo/multi-region-attention &&
#   pip3 install -r requirements.txt &&
#   cp -r models/* /project/models-pv/
# apt-get update && \
# apt-get install -y git && \
# git clone https://github.com/mahfuzalhasan/multi-region-attention /opt/repo/mra && \
# apt update && \
# echo 'Commands executed successfully.' && \
# sleep infinity

# cd /opt/repo/multi-region-attention && \
# pip3 install -r requirements.txt && \